name: deploy actions
on:
  push:
    branches: ["deploy"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "deploy"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
        working-directory: app
      - run: npm run build --if-present
        working-directory: app
      - uses: actions/upload-artifact@v3
        with:
          path: app/out
      - uses: actions/upload-pages-artifact@v1
        with:
          path: app/out
