name: deploy actions
on:
  push:
    branches: ["deploy"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "deploy"
      - run: ls -a
      - run: cd app
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'app/package.json'
      - run: npm ci
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          path: app/out
      - uses: actions/upload-pages-artifact@v1
        with:
          path: app/out
      - name: show all directories and files
        run: ls -a
